### PR TITLE
Create Froto.TypeProvider NuGet Package

### PR DESCRIPTION
**Pull request by takemyoxygen**

### CODE REVIEW

**Comment by takemyoxygen** [comment]
@ctaggart Could you have a look at the failed build? Might that be caused by different line endings?

**Comment by takemyoxygen** [comment]
@ctaggart nevermind :) It was failing because those source files don't exist in the repository: they are restored via paket. Ignored `paket-files` from source indexing for now.

**Comment by ctaggart** [comment]
That makes sense. :+1:

**Comment by ctaggart** [comment]
Thanks again @takemyoxygen. I'm looking to publish 0.4.0 soon.

**Pull request merged**
