### PR TITLE
Initial implementation of the type provider

### PR DESCRIPTION
**Pull request by jhugard**
[Work in Progress]

Implement a .proto Type Provider for F# (#49). 

Initial import of the type provider source code from [ProtoTypes repository](https://github.com/takemyoxygen/ProtoTypes).

* Initial import of the type provider from ProtoTypes
* Fix compilation errors
* Rename project folder
* Fix namespaces in TypeProvider project
* Normalize module definitions in TypeProvider project
* Add project for type provider unit tests
* Fix version of FSharp.Core used by type provider tests
* Import unit tests for the type provider
* Fix fixed/sfixed types serialization
* Recalculate SerializedLength of Message every time

**Still to do:**

- [x] Import tests
- [x] Change repeated and map properties from mutable ones of type list<T> or IReadOnlyDictionary<T, K> to read-only properties of type ResizeArray<T> and IDictionary<T, K>
- [x] Fix compiler warnings
- [x] Valid default values instead of nulls ("" for string, empty collections for repeated and map fields)
- [x] Null checks when serializing
- [x] Exception type
- [x] Non-nested enums support
- [x] Setup NuGet package creation (e.g. `Froto.TypeProvider`) 
- [x] Documentation and samples

### CODE REVIEW

**Comment by jhugard** [comment]
Linux build appears to be failing for several reasons:
- [ ] Mono only supports up to .NET 4.5 (not 4.5.2)
- [ ] Namespace issues in Froto.TypeProvider after downgrading to .NET 4.5; might be related to having a `Core` subdirectory.
- [ ] TravisCI build times out in unit tests.  Cause unknown, but might be when build gets a slow VM.

**Comment by takemyoxygen** [comment]
OK, so let's keep the backlog of all things that need to be done in order to have a minimal releasable version of the type provider.

I'll have a look at failing builds. I think latest mono should support .NET 4.6. I constantly use mono on my local machine and it build works fine for me.

**Comment by takemyoxygen** [comment]
I enabled per-assembly unit tests parallelization and increased the timeout. The build is green now.
However, it's not clear why tests failed in the first place. Normally it takes <10 seconds on Travis, but when it failed it took >5 minutes.

**Comment by jhugard** [comment]
@takemyoxygen What linux distro are you on? Which build of Mono?

My linux box is archlinux with mono 4.4.0.40-2.  The build doesn't appear happy:
---------------------------------------------------------------------
  1) Building /home/jhugard/dev/froto/Froto.sln failed with exitcode 1.
  2) FS1108: /home/jhugard/dev/froto/TypeProvider.Test/TypeProviderTests.fs(42,5): The type 'Attribute' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
---------------------------------------------------------------------

From monodevelop 5.10.1, I get something similar:
/usr/lib/mono/4.5/Microsoft.Common.targets: Warning: TargetFrameworkVersion 'v4.5.2' not supported by this toolset (ToolsVersion: 4.0). (Froto.TypeProvider)

**Comment by takemyoxygen** [comment]
@jhugard I'm actually using OS X (10.11.5) with mono `mono-4.4.0-branch-c7-baseline/5995f74`. I didn't really expect that the same version of mono might support different versions of .NET on different platforms.

Anyway, in this case, I don't see any disadvantages in downgrading `Froto.TypeProvider` to 4.5

**Comment by takemyoxygen** [comment]
@jhugard One more thing, Travis CI is green which means Debian with mono `Nightly 4.4.1.0/4747417` also supports .NET 4.5.2.

Can you maybe check which version of XBuild is used in your case?

**Comment by jhugard** [comment]
Hmm... still failing.  Not sure what the problem is...

`/home/jhugard/dev/froto/TypeProvider.Test/TypeProviderTests.fs(42,5): error FS1108: The type 'Attribute' is required here and is unavailable. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
`

**Comment by takemyoxygen** [comment]
@jhugard that was weird. I restarted Travis CI for a few times before builds became green. There was `ThreadAbortException` somewhere when finalizing `Froto.Serialization.Tests`. Might be a mono hiccup.

**Comment by jhugard** [comment]
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Clean      00:00:00.1221733
Build      00:00:54.8094055
UnitTest   00:00:07.8692268
Default    00:00:00.0000426
Total:     00:01:02.8624362
Status:    Ok
---------------------------------------------------------------------

**Comment by takemyoxygen** [comment]
@jhugard This is on your linux box?

**Comment by jhugard** [comment]
@takemyoxygen Yup.  Build seems to be working fine now after the latest changes.

**Comment by takemyoxygen** [comment]
@jhugard I'm trying to prepare a NuGet package with the type provider, but build always fails on Windows (it fails on master for me as well, so I don't think it's caused by any changes introduced in this PR):
```
Running build failed.
Error:
System.Exception: Could not detect package version for FParsec ---> System.Exception: Package FParsec was not found.
   at Fake.NuGetHelper.version@113.Invoke(String message) in C:\code\FAKE\src\app\FakeLib\NuGet\NugetHelper.fs:line 113
   at Fake.NuGetHelper.GetPackageVersion(String deploymentsDir, String package) in C:\code\FAKE\src\app\FakeLib\NuGet\NugetHelper.fs:line 113
   --- End of inner exception stack trace ---
   at Fake.NuGetHelper.GetPackageVersion(String deploymentsDir, String package) in C:\code\FAKE\src\app\FakeLib\NuGet\NugetHelper.fs:line 127
   at FSI_0005.Build.clo@94-11.Invoke(NuGetParams p) in Y:\dev\code\takemyoxygen-froto\build.fsx:line 95
   at Fake.NuGetHelper.NuGet(FSharpFunc`2 setParams, String nuspecOrProjectFile) in C:\code\FAKE\src\app\FakeLib\NuGet\NugetHelper.fs:line 387
   at FSI_0005.Build.clo@92-10.Invoke(Unit _arg8) in Y:\dev\code\takemyoxygen-froto\build.fsx:line 94
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 484
System.Exception: Could not detect package version for FParsec ---> System.Exception: Package FParsec was not found.
   at Fake.NuGetHelper.version@113.Invoke(String message) in C:\code\FAKE\src\app\FakeLib\NuGet\NugetHelper.fs:line 113
   at Fake.NuGetHelper.GetPackageVersion(String deploymentsDir, String package) in C:\code\FAKE\src\app\FakeLib\NuGet\NugetHelper.fs:line 113
   --- End of inner exception stack trace ---
   at Fake.NuGetHelper.GetPackageVersion(String deploymentsDir, String package) in C:\code\FAKE\src\app\FakeLib\NuGet\NugetHelper.fs:line 127
   at FSI_0005.Build.clo@94-11.Invoke(NuGetParams p) in Y:\dev\code\takemyoxygen-froto\build.fsx:line 95
   at Fake.NuGetHelper.NuGet(FSharpFunc`2 setParams, String nuspecOrProjectFile) in C:\code\FAKE\src\app\FakeLib\NuGet\NugetHelper.fs:line 387
   at FSI_0005.Build.clo@92-10.Invoke(Unit _arg8) in Y:\dev\code\takemyoxygen-froto\build.fsx:line 94
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 484
```

FAKE fails at [this line](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/NuGet/NugetHelper.fs#L112) and it looks to me that this failure is expected.

Basically, FAKE calls `Directory.GetDirectories("./packages", "FParsec.*")` which doesn't find "FParsec" folder on Windows (but does return on Mono).

I'm not quite sure how and why it works on appveyor. Any ideas? Maybe I'm missing something obvious?

**Comment by takemyoxygen** [comment]
@jhugard @ctaggart I implemented everything I planned.  Currently, type provider has few [limitations](https://github.com/ctaggart/froto/blob/type-provider/docs/type-provider/type-provider.md#limitations), but I think it can still be merged to master and released.

**Comment by xenocons** [comment]
Just to add to the limitations, the following .proto produces the error `The type provider 'Froto.TypeProvider.ProtocolBuffersTypeProviderCreator' reported an error: Definition of message "BookAuthor" can't be found.`

```
message BookAuthor {
  optional string name = 1;
}

message BookDetails {
  optional BookAuthor author = 9; 
}
```

**Comment by takemyoxygen** [comment]
@xenocons thanks for reporting that, I'll have a look. To me it looks like it should work.

**Comment by xenocons** [comment]
As a workaround, the following nested type appears to work.
```
message BookDetails {
  message BookAuthor {
    optional string name = 1;
  }
  optional BookAuthor author = 9; 
}
```

**Comment by ctaggart** [comment]
Great news @takemyoxygen! It looks like you got some feedback and a couple of minor issues to work though. Do you want to merge this now and file those as bugs? How do you want to proceed? I'm on vacation this week, but I can probably help release this if needed.

**Comment by takemyoxygen** [comment]
@ctaggart I'll fix the issue tomorrow and after that, the PR can be merged and released whenever you have time.

**Comment by takemyoxygen** [comment]
@xenocons The issue you reported should be fixed now. Could you check if it now works for you?

**Comment by xenocons** [comment]
@takemyoxygen this is fixed, nice work :). 

I do note an interesting side issue, (which is not really to do with this type provider, and probably wont affect general users) but it seems there is some assembly caching going on that makes it hard to check new type provider code, as in, after you fixed this i did a fresh git clone and build, made sure that my project references the newly built type provider DLLs, and the same scope issue occurred, I did a solution clean, still the same scope issue. I opened FSI and manually referenced the type provider DLLs, and everything worked fine.... 

I then went back to the type provider code and had a look at how the Runtime Caching works, noting that it appears to invalidate the cache if the .proto file changes, so I went and manually changed the proto file to something unparseable. Then, the type provider threw a new exception, so I modified the .proto file back, assuming the old cached .dll was invalidated, but I got the same error! The fix was to restart visual studio, which killed the cache.

**Comment by takemyoxygen** [comment]
@xenocons Visual Studio always locks dlls with type providers, so indeed, the only solution is to restart VS which is quite inconvenient for testing and debugging.

**Comment by takemyoxygen** [comment]
@ctaggart I guess, this branch is ready to be released. I'll continue working on the type provider later in separate branches/PRs

**Comment by ctaggart** [comment]
Nice work @takemyoxygen!

**Pull request merged**
