### PR TITLE
support for root Enums

### PR DESCRIPTION
**Pull request by agbogomolov**
add support for root Enums

### CODE REVIEW

**Comment by jhugard** [comment]
The code itself looks good, but would you mind adding a unit test to Froto.Parser.Test/TestModel.fs?

**Comment by agbogomolov** [comment]
done

**Comment by ctaggart** [comment]
:+1: Looks good to me. Thanks for your contribution! @jhugard, I'll let you review and hit the merge button.

**Comment by jhugard** [comment]
Looks good to me too... thank you!

**Pull request merged**
